# name: App deployment workflow

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Run frontend
#         run: |
#           cd frontend
#           npm install
